name = "open-wegram-bot"
main = "src/worker.js"
compatibility_date = "2023-05-18"
keep_vars = true

[placement]
mode = "smart"

[[kv_namespaces]]
binding = "VERIFIED_USERS"
id = "your-kv-namespace-id"
